spring:
  data:
    mongodb:
      host: "mongodb-container"
      username: "admin"
      password: "password"
      database: "mongodb"
      port: 27017
      authentication-database: admin
  mail:
    host: "host.docker.internal"
    port: 8585
    username: "admin"
    password: "password"
    protocol: "smtp"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: false
    default-encoding: UTF-8
mongock:
  change-logs-scan-package:
    - ru.sergey.employeeService.migrations